spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://bith2owoojun.cd80kalx5jvt.ap-northeast-2.rds.amazonaws.com/h2o
    username: bith2owoojun
    password: qkrdnwns4534!
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8





